### ISSUE TITLE
Automatically delete job-monitoring when cronjob is deleted

### ISSUE THREAD

**Issue by KqLLL** [cronitorio/cronitor-kubernetes#31]
Request:
The cronitor-kubernetes can automatically create and update job monitors from CronJob, but the controller does not automatically delete the Job-Monitoring when CronJob are deleted.

Idea:
Can a new annotation be added? Users can choose Job-monitoring, which has the same life cycle as cronjobs.

**Comment by jdotjdot** [comment]
Thanks for the feedback -- this is definitely something we've thought about, and an optional annotation per CronJob could work. The problem is it's a bit deceptively complicated, because you need to handle situations where the agent is uninstalled and reinstalled, where the agent is installed in a fresh cluster with the same Cronjob but with a different ID, if the annotation is removed, etc.  We have this on the backburner but we haven't had a enough interested customers yet to properly define what the behavior should be.

Can you describe more about what behavior you'd expect from an annotation like this?
